---
title: "Deliverables and Tasks"
output:
  html_document:
    css: "styles.css"
---

There are 39 deliverables and 55 tasks in our project plan. Here you can examine all of these broken down by date and by the responsible workpackage. Published reports from deliverables can be found on the [AIML4OS page on the EU Funding and Tenders Portal](https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/projects-details/43252476/101146355/SMP?order=DESC&pageNumber=1&pageSize=10&sortBy=es_SortDate&keywords=aiml4os){target="_blank"}.

## Deliverables

```{r , echo=F  }

deliv <- readRDS('deliv_tasks_resources/deliv_data.rds')
names(deliv) <- c('Description', 'Organisation', 'Workpackage', 'ID' , 'Title' , 'Due Date')
deliv$Workpackage <- as.character(deliv$Workpackage )
deliv$Workpackage <- factor(deliv$Workpackage, levels = as.character(1:13))
deliv$Organisation <- factor(deliv$Organisation)

DT::datatable(deliv , 
              filter = 'top',
              rownames = F,
              options = list(pageLength = 5))
```

## Tasks

```{r , echo=F  }

tasks <- readRDS('deliv_tasks_resources/task_data.rds')
names(tasks) <- c('Workpackage', 'ID' , 'Start Date' , 'End Date', 'Description')
tasks <- tasks[ , c('Description','Workpackage', 'ID' , 'Start Date' , 'End Date')]
tasks$Workpackage <- as.character(tasks$Workpackage)
tasks$Workpackage <- factor(tasks$Workpackage, levels = as.character(1:13))

DT::datatable(tasks , 
              filter = 'top',
              rownames = F,
              options = list(pageLength = 5))
```

<br>
