---
pagetitle: "Knowledge Repository"
date-modified: last-modified
---

## Knowledge Repository and Training Materials

WP6 is advancing towards creating a comprehensive knowledge repository and an extensive range of training materials. These resources aim to support stakeholders across various sectors, providing valuable educational content and standardized materials for the application of AI/ML techniques in different fields. The initial task involves researching topics to include in the knowledge repository: general ML and AI topics, task-driven use cases, best practices, and specialized techniques related to data handling and big data management. Additionally, SSPCloud will host various "cards" for each topic, making the information easily accessible. The second task is dedicated to compiling an inventory of ready-to-use training materials. Early results show a collection including about 20 files (slides, PDFs, and scripts), 11 online courses hosted by NSIs, and 13 courses and books hosted by other institutions. These materials primarily focus on introducing data science and ML concepts, Python and R programming, and best practices for ML workflows.

Looking ahead, other tasks involves listing additional training materials, gradual transfer of data to the repository and training sessions.



## Resources 

- [Guide to creating resources for SSPCloud users](https://aiml4os.github.io/training-material-starting-pack/)


---

<span style ="color:grey; font-size: 13px;">
  Last updated: {{< meta date-modified >}}
</span>
