
# Project Management & Coordination


The aim of this work package is to achieve the overall objectives of the AIML4OS project, building on collaborative synergies among the members of the consortium, and through pro-active communication exchange and involvement of NSIs and external partners within and beyond the consortium. The Central Statistics Office (CSO), Ireland, are leading this coordination workpackage.

The specific objectives are to support, coordinate and facilitate the consortium activities in the project, while also taking measures to ensure adequate quality levels of the outputs that can be realised and remain sustainable across the whole ESS. 

Project management techniques will be used to monitor the progress of the project. WP1 will ensure that scheduled activities are carried out on time and that priorities will be respected. WP1 will also provide feedback to Eurostat.

## Resources

- [AIML4OS on CSO Website](https://www.cso.ie/en/methods/researchatthecso/aiandmachinelearningforofficialstatisticsaiml4os/){target="_blank"}
