

# Imputation


The main objectives in this work package are to develop, test, and, if shown successful, implement AI/ML-based solutions for imputation processes. We propose three tasks.

**Task 9.1 Methodological developments:** the goal is to identify and develop methodological proposals aligned and integrated in the statistical production process, which will be tested with specific datasets, populations, and variables. In this first task we include all the preliminary work such as literature review, assessment of methods and proposals to approach each problem, etc. Next, this task also entails the execution and test of the identified solutions for each problem. The work will be devoloped following this research tracks: Early imputation, post-collection imputation, imputation beyond the sample.

**Task 9.2 Development of PoC/MVP/prototypes and preparation for deployment in production:** if proved successful, the proposals will be promoted to proofs of concept (PoC), minimum viable products (MVP), or prototypes so that feedback can be easily distilled for WP5 on standards, methodological and implementation frameworks. The last goal is to design and implement a CD/CI modular process as close as possible to production conditions to identify the needs for infrastructure, thus serving as input for the ESS AI/ML Lab (WP3).

**Task 9.3 Quality aspects:** The impact of this use case on new statistical products is clear in the form of possible new experimental statistics but also in methodology terms in order to improve the quality of the process in the current statistical products in relation to timeliness, granularity and accuracy.  Quality will be taken into consideration all along the development of the use case.

The duration of the whole work package is estimated in 48 months and with 12 countries participants: Spain (Work Package Leader), Germany, Netherlands, Poland, Portugal, Slovenia, Italy, Austria, Luxemburg, Denmark, Cyprus, Ireland (Coordinator of the project).

## Completed Deliverables

- [**Deliverable 9.1**](https://github.com/AIML4OS/WP9_D9.1/blob/main/main.pdf){target="_blank"} - Methodological aspects from use cases in Machine Learning techniques for early imputation in the production of official statistics
