
# Knowledge Repository

This package aims to provide a coherent set of resources and materials for training and knowledge sharing on this project. Central to this is building up a knowledge repository in the form of a single online platform dedicated to the official statistics community and ensuring materials are freely available. The role of the repository is to make the official statistics community familiar with AI/ML solutions and encourage the community to use these solutions for specific statistical products. Standardized training materials about the use of AI/ML methods will be stored in the platform in many forms, such as notebooks, scripts, presentations, sample databases, and possibly several programming languages such as Python and R. The training materials (in English and national languages) will enable self-studying. 

Training will be carried out on the technical aspects of using the platform. In addition, workshops will be held to introduce AI/ML techniques for statistical products. Funathons, which are non-competitive hackathons, will be held to promote the platform and the use of AI/ML in official statistics. Participants of Funathons will use ML methods for practical tasks connected with the everyday activities of Official Statistics.

We will collaborate closely with the other Work Packages. Training materials will range from topics for beginners to state-of-the-art solutions, following best practices and standards. This work package will promote use cases by arranging workshops and other training as required.

## Resources

- [A repository of useful resources](../chapters/useful_links2.qmd) which are related to the topics covered by AIML4OS. 
- [Link to funathon project 1 - Predicting Housing Prices](https://aiml4os.github.io/funathon-project1/){target="_blank"}
- [Link to funathon project 2 - Automatic Coding for NACE Classification](https://aiml4os.github.io/funathon-project2/){target="_blank"}
- [Link to funathon project 3 - Satellite Image Segmentation with Deep Learning](https://aiml4os.github.io/funathon-project3/){target="_blank"}
- [Guide to creating resources for SSPCloud users](https://aiml4os.github.io/training-material-starting-pack/){target="_blank"}
- [Guide for course creators in setting up effective courses that efficiently help participants learn new skills](https://github.com/AIML4OS/training-material-starting-pack/blob/main/course_guide.md){target="_blank"}
- [Template for training material in Quarto for R users](https://aiml4os.github.io/AIML4OS-template-quarto-r/){target="_blank"}
- [Template for training material in Quarto for Python users](https://aiml4os.github.io/AIML4OS-template-quarto-python/index.html){target="_blank"}
