

# News


## European Conference on Quality in Official Statistics 2026

We had over 20 presentations at the [European Conference on Quality in Official Statistics (Q2026)](https://www.q2026.hr/){target="_blank"}, which took place in Šibenik, Croatia, between 3rd and 5th of June 2026. 

#### Special sessions for AIML4OS at Q2026

[**Session 21, Thursday, 14:15**](https://www.q2026.hr/programme/conference-programme/session-21/){target="_blank"}

- Collaboration for Quality: An Overview of the One Stop Shop for AI and ML for Official Statistics project. (WP1) - [Presentation](https://www.q2026.hr/media/jziha10y/29-eimear-crowley-q2026-presentation.pptx) - [Paper](https://www.q2026.hr/media/hsaod1ub/collaboration-for-quality-an-overview-of-the-one-stop-shop-for-ai-and-ml-for-official-statistics-project.pdf){target="_blank"}
- A New Way to Learn Machine learning and AI: The European AIML4OS Funathon, a Non-competitive Hackathon. (WP6) - [Presentation](https://www.q2026.hr/media/kmuchjs4/presentation-a-new-way-to-learn-machine-learning-and-ai.pptx) 
- MLUtils: An Official Statistics Oriented Common Interface for Machine Learning - [Presentation](https://www.q2026.hr/media/0q5m2qmx/presentation_mlutils.pptx) 
- Generalising Earth Observation AI/ML Pipelines for European Statistics (WP7) - [Presentation](https://www.q2026.hr/media/fg2pfqpn/presentation_special-session0240_remco_paulussen-q2026-generalising-earth-observation-ai-ml-pipelines-for-european-statistics.pptx)

[**Session 16, Thursday, 11:00**](https://www.q2026.hr/programme/conference-programme/session-16/){target="_blank"} 

- From Rules to Algorithms: Rethinking Quality Assurance in the Age of AI - [Presentation](https://www.q2026.hr/media/phshpwhz/q_konf-26-session-16_04-06-2026_museux_final.pptx)
- From the CoP to a Quality Concept for AI/ML in Official Statistics and Back (WP5) - [Presentation](https://www.q2026.hr/media/g24nrngc/presentation_from-the-code-of-practice-to-final.pdf) - [Paper](https://www.q2026.hr/media/gospodsh/paper_from-the-cop-to-a-quality-concept-for-ai-ml-in-official-statistics-and-back.pdf){target="_blank"}
- Technical Perspectives on Quality of the Use of AI in Official Statistics (WP5) - [Presentation](https://www.q2026.hr/media/zqnnthxl/presentation_session-16_technical-perspectives-on-quality-of-the-use-of-ai-in-official-statistics.pptx) - [Paper](https://www.q2026.hr/media/1p0ca2bc/paper_technical-perspectives-on-quality-of-the-use-of-ai-in-official-statistics.pdf){target="_blank"}
- The Methodological View: Current Developments of the Total Machine Learning Error Model (WP5) - [Presentation](https://www.q2026.hr/media/moypo0qp/238_the-methodological-view-current-developments-of-the-total-machine-learning-error-model.pptx) - [Paper](https://www.q2026.hr/media/4hea0vgn/paper_the_methodological_view_of_machine_learning.pdf){target="_blank"}


[**Session 31, Friday, 09:00**](https://www.q2026.hr/programme/conference-programme/session-31/){target="_blank"} 

- Landscape of Text Classification with Machine Learning in Official Statistics: Experiences from the AIML4OS Project (WP10) - [Presentation](https://www.q2026.hr/media/i05m2bga/presentation_landscape_text_classification_session31.pptx) - [Paper](https://www.q2026.hr/media/in5d1qb3/paper_landscape_text_classification_88.pdf){target="_blank"}
- Automatic Coding in Official Statistics: Enhancing Quality Assurance of the Machine Learning Workflow (WP10) - [Presentation](https://www.q2026.hr/media/npihakxy/presentation_103_automatic_coding_in_official_statistics.pptx) - [Paper](https://www.q2026.hr/media/4jilcpgw/103_q2026_automatic_coding.pdf){target="_blank"}
- Measuring Quality of Real and Synthetic Generated Data for Training Statistical Classification Coders (WP10) - [Presentation](https://www.q2026.hr/media/h4nlf2gx/q2026_quality_v1-1.pptx) - [Paper](https://www.q2026.hr/media/disoord4/measuring-quality-of-real-and-synthetic-generated-data-for-training-statistical-classification-coders.pdf){target="_blank"} 
- Using ML and LLMs for NACE Classification (WP10) - [Presentation](https://www.q2026.hr/media/qt2jw1j0/216_q-konf-26_31_using_ml_llms_nace.pptx)

#### All other presentations from AIML4OS at Q2026

- [**Session 3, Wednesday, 11:00**](https://www.q2026.hr/programme/conference-programme/session-3/){target="_blank"} - Luis Ferreira will be presenting on *Unlocking Legacy Statistics with Large Language Models*, based on work carried out by WP12.
- [**Speed Talk Session 3, Wednesday, 13:15**](https://www.q2026.hr/programme/conference-programme/speed-talk-session-3/){target="_blank"} - This session will have a number of presentations from members of AIML4OS, including Alexander Kowarik, Johannes Gussenbauer, Elena Rosa-Perez and Pedro Sousa.
- [**Session 8, Wednesday, 14:15**](https://www.q2026.hr/programme/conference-programme/session-8/){target="_blank"} - Sónia Quaresma will present on the work of the Ecosystem Monitoring workpackage (WP4), with a talk titled *No one is without knowledge except he who asks no questions*. Klaudia Peszat will also present in this session with a talk on *The usefulness of good old ML models in real estate statistics*. 
- [**Session 13, Wednesday, 16:30**](https://www.q2026.hr/programme/conference-programme/session-13/){target="_blank"} - Nina Niederhametner who works with WP10 will present on *Using AI for Automatic Data Extraction and Classification in Official Statistics*. Giulio Massacci will also present in this session with a talk titled: *Who Works in the Green Transition? A Patent-Based Analysis of Occupational Change Using Large Language Models*. The session also includes Luis Sanguiao again, speaking on *High frequency time series imputation with auxiliary data: a deep learning approach*.
- [**Speed Talk Session 10, Thursday, 13:15**](https://www.q2026.hr/programme/conference-programme/speed-talk-session-10/){target="_blank"} Alexandre Cunha from Statistics Portugal (INE) will describe the dataset on inter-firm commercial transactions in Portugal which is used within WP11 for developing a model for reconstructing supply chain networks. Alexandre will discuss the important role of accurate documentation for this highly sensitive dataset. The title of the talk is *Whatever Affects one Directly, Affects all Indirectly*.


## Newsletters

- <a href="https://cros.ec.europa.eu/system/files/2025-03/1.NEWSLETTER%20AIML4OS.pdf" target="_blank">Our first newsletter</a>, highlighting the project launch, upcoming datalab presentation, and planned participation at NTTS 2025.
- <a href="https://cros.ec.europa.eu/system/files/2024-12/2.NEWSLETTER%20AIML4OS.pdf" target="_blank">The second newsletter</a> has info on three in-person meetings that took place, as well as more details on individual workpackages.
- <a href="https://cros.ec.europa.eu/system/files/2025-05/3.NEWSLETTER%20AIML4OS.pdf" target="_blank">Our third newsletter</a> was released after the first year of the project. It looked at plans across all of the workpackages, as well as an update following NTTS 2025.
- <a href="https://cros.ec.europa.eu/system/files/2025-07/4.NEWSLETTER%20AIML4OS.pdf" target="_blank">Newsletter number four</a> reports on an in-person meeting of WP12, more details on WP10, as well as a template for training materials.
- <a href="https://cros.ec.europa.eu/system/files/2025-11/5.NEWSLETTER%20AIML4OS.pdf" target="_blank">Our fifth newsletter</a> has details on a deliverable on citizen-in-the-loop, news on text classification, and progress on reconstruction of supply-chain networks.
- <a href="/resources/newsletters/newsletter_6.pdf" target="_blank">The sixth newsletter</a> has details on a deliverable on citizen-in-the-loop, news on text classification, and progress on reconstruction of supply-chain networks.

## LinkedIn Posts


<div style="width:100%; max-width: 600px;" >
<iframe src="https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7452985254119653376?collapsed=1" 
height="567" 
width="100%" 
frameborder="0" allowfullscreen="" title="Embedded post">
</iframe>
</div>

<div style="width:100%; max-width: 600px;" >
<iframe src="https://www.linkedin.com/embed/feed/update/urn:li:share:7445479879292325888?collapsed=1" 
height="567" 
width=100% 
frameborder="0" allowfullscreen="" title="Embedded post">
</iframe>
</div>

<div style="width:100%; max-width: 600px;" >
<iframe src="https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7393689435994996736?collapsed=1" 
height="567" 
width=100% 
frameborder="0" allowfullscreen="" title="Embedded post">
</iframe>
</div>

<div style="width:100%; max-width: 600px;" >
<iframe src="https://www.linkedin.com/embed/feed/update/urn:li:share:7380985427874328577?collapsed=1" 
height="567" 
width=100% 
frameborder="0" allowfullscreen="" title="Embedded post">
</iframe>
</div>
