# Standards, Methodology & Implementation

A growing number of artificial intelligence/machine learning (AI/ML) applications have emerged within the field of official statistics, that focus on the development of new products and services, on improving decision-making and on increasing the use of new data sources as rapid indicators. While AI/ML has been tested in many statistical offices over the past ten years, the need for standardisation has become apparent with the increasing maturity of the applications on the one hand and the frequency of their use on the other. This is not a one-size-fits-all solution for all use cases, but standards are valuable up to a certain level. Also from a methodological point of view, some progress has been made in recent years, however more research is needed to create well established AI/ML methods. Clearly, blindly applying AI/ML techniques does not suffice when one wants to produce a high quality output. Finally, although available standards and methodological frameworks have the potential to greatly increase the sustainability of AI/ML applications in official statistics, for these to make an impact, it is critical that there are efficient and practical ways to go from theory to practical implementation.

In order to improve and to further develop the use of machine learning in official statistics, this work package on standards, methodological and implementation frameworkshas the following goals: 

1. Generalise knowledge and identify norms and best practices for developing and operating AI/ML based solutions in official statistics; 
2. develop methodological and implementation guidelines for applying AI/ML in the production of official statistics; 
3. achieve standardisation in applying AI/ML based solutions in official statistics; 
4. support the transition from the theoretical and experimental use of AI/ML to the practical implementation of AI/ML in the production of official statistics.
